(()=>{const A=window.API||'https://backend-ruc-1.onrender.com',E=window.escapeHtml||((v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])));const N=v=>new Intl.NumberFormat('es-PY',{maximumFractionDigits:2}).format(Number(v||0));const J=async(u,o={})=>{const r=await fetchApi(A+u,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Error');return d};const P=(u,b,m='POST')=>J(u,{method:m,headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const V=id=>document.getElementById(id)?.value||'';let rows=[],cuentas=[],unidades=[];let editando=null,contItem=null;

function css(){if(document.getElementById('erp-inv-master-css'))return;const z=document.createElement('style');z.id='erp-inv-master-css';z.textContent='.inv-master{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(300px,.7fr);gap:16px}.inv-panel{background:#fff;border:1px solid var(--gris-borde);border-radius:16px;padding:18px}.inv-panel h3{color:var(--azul);font-size:1rem;margin-bottom:5px}.inv-help{color:var(--texto-suave);font-size:.76rem;margin-bottom:16px}.inv-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.inv-grid .full{grid-column:1/-1}.inv-grid label{display:block;font-size:.7rem;font-weight:700;color:var(--texto-suave);margin-bottom:4px}.inv-grid input,.inv-grid select{width:100%;padding:9px 10px;border:1px solid var(--gris-borde);border-radius:8px}.inv-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.inv-status{padding:5px 9px;border-radius:999px;font-size:.68rem;font-weight:800}.inv-ok{background:#e7f7ee;color:#167346}.inv-pend{background:#fff4df;color:#986000}.inv-muted{color:var(--texto-suave);font-size:.75rem}.inv-table-wrap{overflow:auto}.inv-table{width:100%;border-collapse:collapse;font-size:.76rem}.inv-table th,.inv-table td{padding:9px 7px;border-bottom:1px solid var(--gris-borde);text-align:left;white-space:nowrap}.inv-table th{font-size:.65rem;color:var(--texto-suave)}.inv-accounting-box{margin-top:16px;border-top:1px solid var(--gris-borde);padding-top:16px}.inv-accounting-box h4{color:var(--azul);margin-bottom:12px}.inv-accounting-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.inv-accounting-grid label{display:block;font-size:.68rem;font-weight:700;color:var(--texto-suave);margin-bottom:4px}.inv-accounting-grid input,.inv-accounting-grid select{width:100%;padding:9px;border:1px solid var(--gris-borde);border-radius:8px}.inv-note{background:#f7f9fc;border:1px solid var(--gris-borde);border-radius:10px;padding:10px;font-size:.72rem;color:var(--texto-suave);margin-bottom:12px}@media(max-width:1000px){.inv-master{grid-template-columns:1fr}}@media(max-width:650px){.inv-grid,.inv-accounting-grid{grid-template-columns:1fr}.inv-grid .full{grid-column:auto}}';document.head.appendChild(z)}

function shell(){const main=document.querySelector('main.contenido');if(!main)return;
 let v=document.getElementById('vista-inventarios');if(!v){v=document.createElement('section');v.className='vista';v.id='vista-inventarios';main.appendChild(v)}
 v.innerHTML='<h2 class="titulo-seccion">Maestro de Artículos</h2><p class="subtitulo">Catálogo único de KAKUAA. El artículo se crea una sola vez y queda disponible para Compras, Ventas, Inventarios y Contabilidad.</p><div class="inv-master"><div><div class="inv-panel"><h3 id="inv-form-title">Nuevo artículo</h3><p class="inv-help">Definí la identidad operativa y el método de costeo.</p><div class="inv-grid"><div><label>Código interno *</label><input id="ivc" maxlength="40"></div><div><label>Descripción / nombre *</label><input id="ivn"></div><div><label>Unidad de medida *</label><select id="ivu"></select></div><div><label>Tipo IVA *</label><select id="ivi"><option value="0">Exento 0%</option><option value="5">5%</option><option value="10" selected>10%</option></select></div><div><label>Método de costeo *</label><select id="ivcost"><option value="PPP">PPP — Precio Promedio Ponderado</option><option value="PEPS">PEPS — Primero en Entrar, Primero en Salir</option></select></div><div><label>Stock mínimo</label><input id="ivm" type="number" min="0" step=".01" value="0"></div><div><label>Precio base de venta</label><input id="ivp" type="number" min="0" step=".01" value="0"></div><div><label>Control de stock</label><select id="ivinv"><option value="1">Sí, inventariable</option><option value="0">No, servicio / no stock</option></select></div><div class="full"><label>Descripción adicional</label><input id="ivd"></div><div><label>Estado</label><select id="ivestado"><option value="1">Activo</option><option value="0">Inactivo</option></select></div></div><div class="inv-actions"><button class="btn btn-verde" onclick="ERPInventarios.guardar()">＋ Guardar artículo</button><button class="btn btn-gris" onclick="ERPInventarios.cancelar()">Cancelar</button></div></div></div><div class="inv-panel"><h3>Resumen</h3><div id="inv-k" class="erp-module-grid"></div><div class="inv-note">📦 El método de costeo se utiliza en la ficha de mercaderías y en las salidas de inventario.</div></div></div><div class="inv-panel" style="margin-top:16px"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><h3>Artículos registrados</h3></div><input id="ivq" placeholder="🔎 Buscar código o descripción" oninput="ERPInventarios.render()" style="padding:9px;border:1px solid var(--gris-borde);border-radius:8px;min-width:240px"></div><div class="inv-table-wrap" style="margin-top:12px"><table class="inv-table"><thead><tr><th>Código</th><th>Artículo</th><th>Costeo</th><th>Unidad</th><th>Existencia</th><th>Costo</th><th>Contabilidad</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="ivtb"></tbody></table></div></div>';
 let d=document.getElementById('vista-inventarios-depositos');if(!d){d=document.createElement('section');d.className='vista';d.id='vista-inventarios-depositos';main.appendChild(d)}
 d.innerHTML='<h2 class="titulo-seccion">Definición de Depósitos</h2><p class="subtitulo">Creá los depósitos físicos donde se almacenan los artículos inventariables.</p><div class="inv-panel"><div class="inv-grid"><div><label>Código *</label><input id="dep-cod"></div><div><label>Nombre *</label><input id="dep-nom"></div><div class="full"><label>Ubicación</label><input id="dep-ubi"></div></div><div class="inv-actions"><button class="btn btn-verde" onclick="ERPInventarios.crearDeposito()">＋ Crear depósito</button></div><div class="inv-table-wrap" style="margin-top:18px"><table class="inv-table"><thead><tr><th>Código</th><th>Nombre</th><th>Ubicación</th><th>Existencia</th><th>Estado</th><th>Acción</th></tr></thead><tbody id="deptb"></tbody></table></div></div>';
 let r=document.getElementById('vista-reporte-inventario');if(!r){r=document.createElement('section');r.className='vista';r.id='vista-reporte-inventario';main.appendChild(r)}
 r.innerHTML='<h2 class="titulo-seccion">Reporte de Inventario por Depósito</h2><p class="subtitulo">Ficha de mercaderías con movimiento físico y monetario, según PEPS o PPP.</p><div class="inv-panel"><div class="inv-grid"><div><label>Depósito</label><select id="repdep"></select></div><div><label>Artículo inventariable</label><select id="repitem"></select></div></div><div id="rephead" class="inv-note" style="margin-top:14px"></div><div class="inv-table-wrap"><table class="inv-table"><thead><tr><th>Fecha</th><th>Descripción</th><th>Precio unitario</th><th>Precio medio</th><th>Mov. Inventario</th><th>Saldo inventario</th><th>Debe</th><th>Haber</th><th>Saldo monetario</th></tr></thead><tbody id="reptb"></tbody></table></div></div>';
 let c=document.getElementById('vista-control-stock');if(!c){c=document.createElement('section');c.className='vista';c.id='vista-control-stock';main.appendChild(c)}
 c.innerHTML='<h2 class="titulo-seccion">Control de Stock de Inventario</h2><p class="subtitulo">Compará el stock del sistema con el conteo físico y generá ajustes cuando exista diferencia.</p><div class="inv-panel"><div class="inv-grid"><div><label>Depósito</label><select id="ctrldep"></select></div></div><div class="inv-table-wrap" style="margin-top:14px"><table class="inv-table"><thead><tr><th>Código</th><th>Artículo</th><th>Sistema</th><th>Físico</th><th>Diferencia</th><th>Costo</th><th>Acción</th></tr></thead><tbody id="ctrltb"></tbody></table></div></div>';
 let cta=document.getElementById('vista-contabilidad-articulos');if(!cta){cta=document.createElement('section');cta.className='vista';cta.id='vista-contabilidad-articulos';main.appendChild(cta)}
 cta.innerHTML='<h2 class="titulo-seccion">Parametrización contable de artículos</h2><p class="subtitulo">Los artículos nacen en Inventarios. Contabilidad solamente define sus conceptos presupuestarios y cuentas.</p><div class="inv-panel"><div class="inv-note">📚 Completá las seis imputaciones para habilitar el circuito contable del artículo.</div><div id="inv-cont-lista" class="inv-table-wrap"></div><div id="inv-cont-form"></div></div>';
 let um=document.getElementById('vista-unidades-medida');if(!um){um=document.createElement('section');um.className='vista';um.id='vista-unidades-medida';main.appendChild(um)}
 um.innerHTML='<h2 class="titulo-seccion">Definición de Unidades de Medida</h2><p class="subtitulo">Catálogo central de unidades que utiliza Inventarios, Compras y Ventas.</p><div class="inv-panel"><div class="inv-grid"><div><label>Código *</label><input id="um-cod"></div><div><label>Nombre *</label><input id="um-nom"></div><div><label>Abreviatura</label><input id="um-abr"></div></div><div class="inv-actions"><button class="btn btn-verde" onclick="ERPInventarios.crearUnidad()">＋ Crear unidad</button></div><div class="inv-table-wrap" style="margin-top:18px"><table class="inv-table"><thead><tr><th>Código</th><th>Nombre</th><th>Abreviatura</th><th>Estado</th></tr></thead><tbody id="umtb"></tbody></table></div></div>';
}
async function catalogos(){try{unidades=await J('/api/compras/unidades-medida');const u=document.getElementById('ivu');if(u){u.innerHTML='<option value="">Seleccioná una unidad *</option>'+(unidades||[]).filter(x=>Number(x.activo)!==0).map(x=>'<option value="'+x.id+'">'+E(x.codigo)+' — '+E(x.nombre)+'</option>').join('')}}catch(_){}try{cuentas=await J('/api/contabilidad/cuentas')}catch(_){cuentas=[]}}

function render(){const q=(V('ivq')).toLowerCase();const data=rows.filter(x=>(String(x.codigo)+' '+String(x.nombre)).toLowerCase().includes(q));const tb=document.getElementById('ivtb');if(!tb)return;tb.innerHTML=data.map(x=>'<tr><td><strong>'+E(x.codigo)+'</strong></td><td>'+E(x.nombre)+'</td><td>'+E(x.unidad_codigo||x.unidad_nombre||'—')+'</td><td>'+N(x.tipo_iva)+'%</td><td>'+N(x.existencia)+'</td><td>'+N(x.precio_base)+'</td><td><span class="inv-status '+(x.contabilidad_configurada?'inv-ok':'inv-pend')+'">'+(x.contabilidad_configurada?'Configurado':'Pendiente')+'</span></td><td>'+((Number(x.activo)!==0)?'Activo':'Inactivo')+'</td><td><button class="btn btn-gris btn-pequeno" onclick="ERPInventarios.editar('+x.id+')">Editar</button> <button class="btn '+(Number(x.activo)!==0?'btn-amarillo':'btn-verde')+' btn-pequeno" onclick="ERPInventarios.estado('+x.id+','+(Number(x.activo)===0)+')">'+(Number(x.activo)!==0?'Inactivar':'Reactivar')+'</button> <button class="btn btn-azul btn-pequeno" onclick="ERPInventarios.contabilidad('+x.id+')">Contabilidad</button></td></tr>').join('')||'<tr><td colspan="9">No hay artículos registrados.</td></tr>';const k=document.getElementById('inv-k');if(k){const activos=rows.filter(x=>Number(x.activo)!==0).length;const conf=rows.filter(x=>x.contabilidad_configurada).length;k.innerHTML='<div class="erp-card"><div class="erp-muted">Artículos</div><div class="erp-kpi">'+activos+'</div></div><div class="erp-card"><div class="erp-muted">Configurados</div><div class="erp-kpi">'+conf+'</div></div><div class="erp-card"><div class="erp-muted">Pendientes</div><div class="erp-kpi">'+(activos-conf)+'</div></div>'}}

async function cargar(){try{rows=await J('/api/inventarios/items');render();renderContabilidad()}catch(e){alert(e.message)}}
function limpiar(){editando=null;['ivc','ivn','ivm','ivp','ivd'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=id==='ivm'||id==='ivp'?'0':''});const u=document.getElementById('ivu');if(u)u.value='';document.getElementById('ivi').value='10';document.getElementById('ivinv').value='1';document.getElementById('ivestado').value='1';document.getElementById('inv-form-title').textContent='Nuevo artículo'}
function editar(id){const x=rows.find(r=>Number(r.id)===Number(id));if(!x)return;editando=id;document.getElementById('ivc').value=x.codigo||'';document.getElementById('ivn').value=x.nombre||'';document.getElementById('ivu').value=x.unidad_medida_id||'';document.getElementById('ivi').value=String(x.tipo_iva??10);document.getElementById('ivm').value=x.stock_minimo??0;document.getElementById('ivp').value=x.precio_base??0;document.getElementById('ivd').value=x.descripcion||'';document.getElementById('ivinv').value=String(x.inventariable??1);document.getElementById('ivestado').value=String(x.activo??1);document.getElementById('inv-form-title').textContent='Editar artículo '+(x.codigo||'');document.getElementById('vista-inventarios').scrollIntoView({behavior:'smooth',block:'start'})}
async function guardar(){const um=unidades.find(x=>Number(x.id)===Number(V('ivu')));const b={codigo:V('ivc').trim(),nombre:V('ivn').trim(),unidad_medida_id:Number(V('ivu'))||null,unidad_codigo:um?.codigo||'',tipo_iva:Number(V('ivi')),stock_minimo:Number(V('ivm')||0),precio_base:Number(V('ivp')||0),descripcion:V('ivd').trim(),inventariable:Number(V('ivinv'))===1};if(!b.codigo||!b.nombre||!b.unidad_medida_id){alert('Código, descripción y unidad de medida son obligatorios.');return}try{if(editando)await P('/api/inventarios/items/'+editando,{...b,activo:Number(V('ivestado'))===1},'PATCH');else await P('/api/inventarios/items',b);alert(editando?'Artículo actualizado.':'Artículo creado.');limpiar();await cargar()}catch(e){alert(e.message)}}
async function estado(id,activo){if(!confirm('¿Querés '+(activo?'reactivar':'inactivar')+' este artículo?'))return;try{await P('/api/inventarios/items/'+id,{activo:activo},'PATCH');await cargar()}catch(e){alert(e.message)}}
function cancelar(){limpiar()}
function selectCuenta(id,val){return'<select id="'+id+'"><option value="">Seleccioná una cuenta</option>'+cuentas.filter(x=>Number(x.imputable)===1&&Number(x.activa)!==0).map(x=>'<option value="'+x.id+'" '+(Number(x.id)===Number(val)?'selected':'')+'>'+E(x.codigo)+' — '+E(x.nombre)+'</option>').join('')+'</select>'}
function renderContabilidad(){const el=document.getElementById('inv-cont-lista');if(!el)return;el.innerHTML='<table class="inv-table"><thead><tr><th>Código</th><th>Artículo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>'+rows.filter(x=>Number(x.activo)!==0).map(x=>'<tr><td>'+E(x.codigo)+'</td><td>'+E(x.nombre)+'</td><td><span class="inv-status '+(x.contabilidad_configurada?'inv-ok':'inv-pend')+'">'+(x.contabilidad_configurada?'Completo':'Pendiente')+'</span></td><td><button class="btn btn-azul btn-pequeno" onclick="ERPInventarios.contabilidad('+x.id+')">Parametrizar</button></td></tr>').join('')+'</tbody></table>'}
function contabilidad(id){const x=rows.find(r=>Number(r.id)===Number(id));if(!x)return;contItem=x;const el=document.getElementById('inv-cont-form');if(!el)return;el.innerHTML='<div class="inv-accounting-box"><h4>'+E(x.codigo)+' · '+E(x.nombre)+'</h4><div class="inv-accounting-grid"><div><label>Concepto presupuestario de Ingreso</label><input id="cp-ing" value="'+E(x.concepto_presupuestario_ingreso||'')+'"></div><div><label>Concepto presupuestario de Egreso</label><input id="cp-egr" value="'+E(x.concepto_presupuestario_egreso||'')+'"></div><div><label>Cuenta Debe — Compra</label>'+selectCuenta('ct-dc',x.cuenta_debe_compra_id)+'</div><div><label>Cuenta Debe — Devolución de Venta</label>'+selectCuenta('ct-dv',x.cuenta_debe_devolucion_venta_id)+'</div><div><label>Cuenta Haber — Venta</label>'+selectCuenta('ct-hv',x.cuenta_haber_venta_id)+'</div><div><label>Cuenta Haber — Devolución de Compra</label>'+selectCuenta('ct-hdc',x.cuenta_haber_devolucion_compra_id)+'</div></div><div class="inv-actions"><button class="btn btn-verde" onclick="ERPInventarios.guardarContabilidad()">💾 Guardar parametrización</button><button class="btn btn-gris" onclick="ERPInventarios.cancelarContabilidad()">Cancelar</button></div></div>';el.scrollIntoView({behavior:'smooth',block:'center'})}
async function guardarContabilidad(){if(!contItem)return;const b={concepto_presupuestario_ingreso:V('cp-ing').trim(),concepto_presupuestario_egreso:V('cp-egr').trim(),cuenta_debe_compra_id:Number(V('ct-dc'))||null,cuenta_debe_devolucion_venta_id:Number(V('ct-dv'))||null,cuenta_haber_venta_id:Number(V('ct-hv'))||null,cuenta_haber_devolucion_compra_id:Number(V('ct-hdc'))||null};if(!b.concepto_presupuestario_ingreso||!b.concepto_presupuestario_egreso||!b.cuenta_debe_compra_id||!b.cuenta_debe_devolucion_venta_id||!b.cuenta_haber_venta_id||!b.cuenta_haber_devolucion_compra_id){alert('Completá los seis parámetros contables.');return}try{await P('/api/inventarios/items/'+contItem.id+'/contabilidad',b,'PATCH');alert('Parametrización contable guardada.');contItem=null;document.getElementById('inv-cont-form').innerHTML='';await cargar()}catch(e){alert(e.message)}}
function cancelarContabilidad(){contItem=null;const e=document.getElementById('inv-cont-form');if(e)e.innerHTML=''}

async function cargarDepositos(){const d=await J('/api/inventarios/depositos');const tb=document.getElementById('deptb');if(tb)tb.innerHTML=d.map(x=>'<tr><td>'+E(x.codigo)+'</td><td>'+E(x.nombre)+'</td><td>'+E(x.ubicacion||'—')+'</td><td>'+N(x.existencia_items)+'</td><td>'+(x.activo?'Activo':'Inactivo')+'</td><td><button class="btn btn-gris btn-pequeno" onclick="ERPInventarios.toggleDeposito('+x.id+','+(x.activo?0:1)+')">'+(x.activo?'Inactivar':'Activar')+'</button></td></tr>').join('');['repdep','ctrldep'].forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML='<option value="">Seleccioná un depósito</option>'+d.filter(x=>x.activo).map(x=>'<option value="'+x.id+'">'+E(x.codigo)+' — '+E(x.nombre)+'</option>').join('')});}
async function crearDeposito(){const b={codigo:V('dep-cod').trim(),nombre:V('dep-nom').trim(),ubicacion:V('dep-ubi').trim()};if(!b.codigo||!b.nombre)return alert('Código y nombre son obligatorios.');try{await P('/api/inventarios/depositos',b);document.getElementById('dep-cod').value='';document.getElementById('dep-nom').value='';document.getElementById('dep-ubi').value='';await cargarDepositos()}catch(e){alert(e.message)}}
async function toggleDeposito(id,activo){try{await P('/api/inventarios/depositos/'+id,{activo:!!activo},'PATCH');await cargarDepositos()}catch(e){alert(e.message)}}
async function cargarReporte(){const dep=V('repdep'),item=V('repitem');if(!dep||!item)return;try{const d=await J('/api/inventarios/reporte/'+dep+'/'+item);document.getElementById('rephead').innerHTML='<strong>'+E(d.item.codigo)+' · '+E(d.item.nombre)+'</strong> · Depósito: '+E(d.deposito.nombre)+' · Método: <strong>'+E(d.metodo_costeo)+'</strong>';document.getElementById('reptb').innerHTML=d.movimientos.map(x=>'<tr><td>'+E(x.fecha)+'</td><td>'+E(x.descripcion)+'</td><td>'+N(x.precio_unitario)+'</td><td>'+N(x.precio_medio)+'</td><td>'+N(x.movimiento_cantidad)+'</td><td>'+N(x.saldo_cantidad)+'</td><td>'+N(x.movimiento_debe)+'</td><td>'+N(x.movimiento_haber)+'</td><td>'+N(x.saldo_monetario)+'</td></tr>').join('')||'<tr><td colspan="9">Sin movimientos.</td></tr>'}catch(e){alert(e.message)}}
async function cargarControl(){const dep=V('ctrldep');if(!dep)return;try{const d=await J('/api/inventarios/control-stock/'+dep);document.getElementById('ctrltb').innerHTML=d.map(x=>'<tr><td>'+E(x.codigo)+'</td><td>'+E(x.nombre)+'</td><td>'+N(x.stock_sistema)+'</td><td><input id="fis-'+x.id+'" type="number" step=".01" value="'+N(x.stock_fisico)+'" style="width:100px"></td><td id="dif-'+x.id+'">0</td><td>'+N(x.costo_promedio)+'</td><td><button class="btn btn-azul btn-pequeno" onclick="ERPInventarios.ajustar('+x.id+','+dep+')">Registrar conteo / ajuste</button></td></tr>').join('')||'<tr><td colspan="7">Sin artículos inventariables.</td></tr>'}catch(e){alert(e.message)}}
async function ajustar(item,dep){const fis=Number(document.getElementById('fis-'+item)?.value||0);if(!confirm('¿Registrar el conteo físico y ajustar el inventario si existe diferencia?'))return;try{const d=await P('/api/inventarios/ajustes',{item_id:item,deposito_id:Number(dep),stock_fisico:fis,observacion:'Ajuste generado desde control de inventario'});alert(d.ajustado?'Ajuste registrado. Diferencia: '+N(d.diferencia):'No existe diferencia.');await cargarControl();await cargar()}catch(e){alert(e.message)}}
async function cargarUnidades(){try{const d=await J('/api/compras/unidades-medida');const tb=document.getElementById('umtb');if(tb)tb.innerHTML=(d||[]).map(x=>'<tr><td>'+E(x.codigo)+'</td><td>'+E(x.nombre)+'</td><td>'+E(x.abreviatura||'—')+'</td><td>'+(x.activo?'Activo':'Inactivo')+'</td></tr>').join('')}catch(e){alert(e.message)}}
async function crearUnidad(){const b={codigo:V('um-cod').trim(),nombre:V('um-nom').trim(),abreviatura:V('um-abr').trim()};if(!b.codigo||!b.nombre)return alert('Código y nombre son obligatorios.');try{await P('/api/compras/unidades-medida',b);document.getElementById('um-cod').value='';document.getElementById('um-nom').value='';document.getElementById('um-abr').value='';await catalogos();await cargarUnidades()}catch(e){alert(e.message)}}

const X={cargar,render,guardar,editar,estado,cancelar,contabilidad,guardarContabilidad,cancelarContabilidad,cargarDepositos,crearDeposito,toggleDeposito,cargarReporte,cargarControl,ajustar,cargarUnidades,crearUnidad,depositos:async()=>{try{const d=await J('/api/inventarios/depositos');const e=document.getElementById('ivdep');if(e)e.innerHTML='<table class="erp-table"><thead><tr><th>Código</th><th>Nombre</th><th>Ubicación</th></tr></thead><tbody>'+d.map(x=>'<tr><td>'+E(x.codigo)+'</td><td>'+E(x.nombre)+'</td><td>'+E(x.ubicacion)+'</td></tr>').join('')+'</tbody></table>'}catch(e){alert(e.message)}}};
window.ERPInventarios=X;
function nav(){const s=document.querySelector('.sidebar');if(s&&!s.querySelector('[data-vista="inventarios"]'))s.insertAdjacentHTML('beforeend','<div class="nav-group"><div class="nav-group-title"><span>📦 Inventarios</span><span class="chevron">⌄</span></div><div class="nav-subitems"><div class="nav-item nav-subitem" data-vista="inventarios" onclick="cambiarVista(\'inventarios\')">Maestro de Artículos</div><div class="nav-item nav-subitem" data-vista="inventarios-depositos" onclick="cambiarVista(\'inventarios-depositos\')">Depósitos</div></div></div>');const f=window.cambiarVista;if(f&&!f._iv){window.cambiarVista=function(v){f(v);if(v==='inventarios')X.cargar();if(v==='inventarios-depositos')X.depositos();if(v==='contabilidad-articulos')renderContabilidad();if(v==='inventarios-depositos')cargarDepositos();if(v==='reporte-inventario'){cargarDepositos();const e=document.getElementById('repitem');if(e)e.innerHTML='<option value="">Seleccioná un artículo</option>'+rows.filter(x=>x.inventariable&&x.activo).map(x=>'<option value="'+x.id+'">'+E(x.codigo)+' — '+E(x.nombre)+'</option>').join('');}if(v==='control-stock')cargarDepositos().then(cargarControl);if(v==='unidades-medida')cargarUnidades()};window.cambiarVista._iv=1}}
function init(){css();shell();nav();catalogos().then(cargar)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();